### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by MingLoan** [kaishin/Gifu#66] opened 2016-05-13 04:12 UTC
Anyone has any suggestions on this crash??

![screen shot 2016-05-13 at 12 10 32](https://cloud.githubusercontent.com/assets/5032142/15237763/ca5f2552-1903-11e6-9e71-0ef787c2aaa1.png)

**Comment by adamszeptycki** [comment] 2016-05-19 14:42
I have similar thing in my Project, surprising enough it happens only on iPhone 6s Plus. And only on device.
I don't have such device at hand to debug this.

**Comment by jellybeansoup** [comment] 2016-05-27 02:12
I'm also experiencing this issue. Despite @adamszeptycki's comment, it isn't limited to the iPhone 6s plus, as I can confirm crashes caused by this problem across multiple devices, both iPhone and iPad alike.

Unfortunately, crashes logged with remote sources aren't capturing a complete stack trace (for some reason), but I've been getting this issue in local testing, so I have been able to witness what I _think_ might be the cause of the issue. Note the additional calls in this screenshot:

<img width="616" alt="screen shot 2016-05-27 at 11 49 17 am" src="https://cloud.githubusercontent.com/assets/869105/15595412/439d8e3c-2402-11e6-9dd4-e15c1c4bbdbb.png">

I haven't fully investigated the issue, but it seems like the `Animator` is trying to load frames before they have completed loading. I'm getting a `fatal error: Index out of range` message printed to the debugger when using an exception breakpoint. I noted that the dispatch queue is processing at the time of the crash:

<img width="618" alt="screen shot 2016-05-27 at 11 49 42 am" src="https://cloud.githubusercontent.com/assets/869105/15595472/b52a49dc-2402-11e6-885d-9d3f2941f901.png">

Hope that's helpful.

**Comment by jellybeansoup** [comment] 2016-05-27 03:19
I believe I've sorted out the cause of this issue, and I've forked the repo and created a pull request (#68) with the fix. It'd be awesome if you both could confirm the fix on your end!

**Comment by kaishin** [comment] 2016-05-28 18:16
Fixed in 79f01b0. Thanks @jellybeansoup!

**Closed by kaishin** 2016-05-28 18:16 UTC
